---
- name: install container
  docker:
    name: "{{docker_swagger_generator_container_name}}"
    image: "swaggerapi/swagger-generator:{{docker_swagger_generator_version}}"
    state: "{{docker_swagger_generator_state}}"
    ports:
      - "{{docker_swagger_generator_web_port}}:8080"

- name: enable apache2 modules
  apache2_module: state=present name={{item}}
  with_items:
    - proxy
    - proxy_http
  notify:
    - docker_swagger_generator_apache2_restart

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-docker-swagger-generator.conf
  notify:
    - docker_swagger_generator_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-docker-swagger-generator.conf creates=/etc/apache2/sites-enabled/100-docker-swagger-generator.conf
  notify:
    - docker_swagger_generator_apache2_restart