---
- name: docker_swagger_generator_apache2_restart
  service:
    name: "{{docker_swagger_generator_apache2_restart_command}}"
    state: restarted
  when: docker_swagger_generator_apache2_exists.stat.exists == true